apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: https://console.cloud.google.com/kubernetes/clusters/details/us-central1-c/cluster-1/details?hl=en&project=project-dev-432815

